# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - HAL-NH24-SV41-chy1105

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_f6c3612f1a334a53a820773c713ffff2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_09668d1804704f0c9a9c736f80bb4b73 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f6c3612f1a334a53a820773c713ffff2 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'HAL-NH24-SV41-chy1105'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2383254833ee4f1dac14dfdd3d79e612 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f6c3612f1a334a53a820773c713ffff2 }}/appsvc/staticsite:${{ github.sha }}'